### ISSUE TITLE
Control + arrow not a detectable option

### ISSUE THREAD

**Issue by artur-szpot** [magmax/python-readchar#120]
Great project, thanks! Works like a charm. Small but useful addition would be to also be able to detect CTRL_UP, CTRL_LEFT, etc. events (perhaps also with other modifiers/for other functional keys?). Unless there is some limitation that prevents it?

**Comment by Cube707** [comment]
a lot of this type of key-combinations are used for shortcuts in terminal emulator, so they are very inconsistent in what actually gets passed on to the program and whats gets captured earlier.

And on the Linux side it gets quite hard to pinpoint the exact character-sequences that make up these more rare key-combinations. Also #24 (though I have no Idea how to tackle that one ...)

But yes, Expanding the key-lists is pretty simple if all the char-sequences are known.

**Comment by artur-szpot** [comment]
Thanks for the prompt reply. It is a technical limitation then, as expected. A pity, but this still remains the best lib I found for my use case, so I'll just have to assign a different key. Best of luck with further development :)

**Comment by Cube707** [comment]
If your applications scope is limited enough that you are sure that the keys work as expected you can just add the constants in your application (`CTRL_UP` would be `"\x00\x8d"` on windows for example). You could even hot-patch the `key` module for your application. 

Its just a different matter for the libary, because adding them will result in people complaining about the keys not working when really its just their terminal-emulator gobbeling them up...

**Comment by Cube707** [comment]
For example, `CTRL_UP` works fine in windows CMD, but not in the VS-code terminal.

**Comment by artur-szpot** [comment]
The app I'm writing is pretty much for personal use, but I like staying true to the sources I'm using, in case I do decide to share it at some point. It's not a major obstacle for me, anyway; I just felt it's an unexpected gap to have and wanted to confirm with you that it's not accidental. Thanks!
